export default {
    darkMode: 'class',
    content: [
        './resources/views/**/*.blade.php',
        './resources/js/**/*.{js,jsx,ts,tsx}',
    ],
    theme: {
        extend: {
            colors: {
                'tertiary-container': '#975d42',
                background: '#fff8f3',
                'on-tertiary-fixed': '#351000',
                'on-tertiary-container': '#ffe9e1',
                'on-secondary-fixed-variant': '#57441b',
                'secondary-fixed-dim': '#dfc38f',
                tertiary: '#7b452d',
                error: '#ba1a1a',
                'primary-fixed': '#ffdbcf',
                outline: '#8b7269',
                'on-tertiary-fixed-variant': '#6c3922',
                'on-primary-fixed-variant': '#812800',
                'on-secondary-container': '#756034',
                'surface-variant': '#f2e0c6',
                'surface-container-highest': '#f2e0c6',
                surface: '#fff8f3',
                'outline-variant': '#dec0b6',
                'surface-container-high': '#f7e6cb',
                'surface-container-lowest': '#ffffff',
                'surface-tint': '#a33d12',
                'primary-fixed-dim': '#ffb59b',
                'on-error': '#ffffff',
                'inverse-surface': '#392f1d',
                'on-secondary-fixed': '#261900',
                'surface-bright': '#fff8f3',
                'on-surface-variant': '#57423b',
                'on-tertiary': '#ffffff',
                'secondary-fixed': '#fcdfa9',
                'on-primary-container': '#ffe9e2',
                'inverse-primary': '#ffb59b',
                'tertiary-fixed-dim': '#ffb696',
                'on-error-container': '#93000a',
                'surface-container': '#fdecd1',
                'on-primary-fixed': '#380d00',
                'surface-dim': '#e9d8be',
                'on-surface': '#231a0a',
                primary: '#943306',
                'inverse-on-surface': '#ffefd6',
                'primary-container': '#b54a1f',
                'secondary-container': '#f9dca6',
                'surface-container-low': '#fff2e0',
                'on-secondary': '#ffffff',
                secondary: '#715b30',
                'tertiary-fixed': '#ffdbcd',
                'on-background': '#231a0a',
                'on-primary': '#ffffff',
                'error-container': '#ffdad6',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '1rem',
                xl: '1.5rem',
                full: '9999px',
            },
            spacing: {
                'stack-md': '24px',
                'stack-sm': '8px',
                'container-max': '1200px',
                'margin-mobile': '28px',
                unit: '4px',
                'stack-lg': '48px',
                gutter: '24px',
                'margin-desktop': '84px',
            },
            fontFamily: {
                'headline-lg-mobile': ['Newsreader'],
                'body-lg': ['Be Vietnam Pro'],
                'label-sm': ['Be Vietnam Pro'],
                'headline-xl': ['Newsreader'],
                'headline-lg': ['Newsreader'],
                'body-md': ['Be Vietnam Pro'],
            },
            fontSize: {
                'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '500' }],
                'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
                'label-sm': ['13px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
                'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
                'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '500' }],
                'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
            },
        },
    },
};
